[project]
name = "chatbot-litellm-chainlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "chainlit>=2.5.5",
    "litellm>=1.71.1",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
]
